name: Discord
on:
  push:
jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: '1497300954352189611'
          webhook_token: 'uzv31cRFzprmTdsEWoRKUKW9MXmBV_-YPiRNkYLeVO_arm815RjnTxTeLWmsn_8yqyi6'
          message: "🚀S2 **Alerta DevOps!**\nNovo commit realizado por: ${{ github.actor }}\nNo repositório: ${{ github.repository }}"
